// src/components/SocialMediaLinks.tsx
import React from 'react';

// Styles
import {Wrapper} from "../styles/SocialMediaLinks.styles";
import {DropShadowImageButton} from "../styles/Utils.styles";

export type Link = {
    image: string,
    url: string,
    text: string
}

type Props = {
    links: Link[];
}

const SocialMediaLinks: React.FC<Props> = ({links}) => (
    <Wrapper>
        {links.map(link => (
            <>
                <a href={link.url} target="_blank" rel="noreferrer">
                    <DropShadowImageButton src={link.image} alt={link.text}/>
                </a>
                <span>{link.text}</span>
            </>
        ))}
    </Wrapper>
);

export default SocialMediaLinks;

// src/lib/components/SocialMediaLinks.svelte
<script lang="ts">
  import links from "../../datas/links";
  import DropShadowImageButton from "./DropShadowImageButton.svelte";
</script>

<div class="flex justify-center m-2 gap-2">
  {#each links as link}
    <a href={link.url} target="_blank" rel="noreferrer">
      <DropShadowImageButton
        src={link.image}
        alt={link.text}
        --desktop-width="55px"
        --mobile-width="40px"
      />
    </a>
    <span class="hidden">{link.text}</span>
  {/each}
</div>
